SRC_DIR = ../src
DEPS_DIR = ../platforms/shared/dependencies

SOURCES_C := \
    $(DEPS_DIR)/miniz/miniz.c \

SOURCES_CXX := \
    $(SRC_DIR)/Audio.cpp \
    $(SRC_DIR)/Cartridge.cpp \
    $(SRC_DIR)/CommonMemoryRule.cpp \
    $(SRC_DIR)/GearboyCore.cpp \
    $(SRC_DIR)/Input.cpp \
    $(SRC_DIR)/IORegistersMemoryRule.cpp \
    $(SRC_DIR)/MBC1MemoryRule.cpp \
    $(SRC_DIR)/MBC2MemoryRule.cpp \
    $(SRC_DIR)/MBC3MemoryRule.cpp \
    $(SRC_DIR)/MBC5MemoryRule.cpp \
    $(SRC_DIR)/Memory.cpp \
    $(SRC_DIR)/MemoryRule.cpp \
    $(SRC_DIR)/MultiMBC1MemoryRule.cpp \
    $(SRC_DIR)/HuC1MemoryRule.cpp \
    $(SRC_DIR)/HuC3MemoryRule.cpp \
    $(SRC_DIR)/MMM01MemoryRule.cpp \
    $(SRC_DIR)/CameraMemoryRule.cpp \
    $(SRC_DIR)/MBC7MemoryRule.cpp \
    $(SRC_DIR)/TAMA5MemoryRule.cpp \
    $(SRC_DIR)/WisdomTreeMemoryRule.cpp \
    $(SRC_DIR)/M161MemoryRule.cpp \
    $(SRC_DIR)/SachenMMC1MemoryRule.cpp \
    $(SRC_DIR)/SachenMMC2MemoryRule.cpp \
    $(SRC_DIR)/FlashcartMemoryRule.cpp \
    $(SRC_DIR)/opcodes.cpp \
    $(SRC_DIR)/opcodes_cb.cpp \
    $(SRC_DIR)/Processor.cpp \
    $(SRC_DIR)/RomOnlyMemoryRule.cpp \
    $(SRC_DIR)/Video.cpp \
    $(SRC_DIR)/VgmRecorder.cpp \
    $(SRC_DIR)/SGB.cpp \
    $(SRC_DIR)/TraceLogger.cpp \
    $(SRC_DIR)/audio/Blip_Buffer.cpp \
    $(SRC_DIR)/audio/Effects_Buffer.cpp \
    $(SRC_DIR)/audio/Gb_Apu.cpp \
    $(SRC_DIR)/audio/Gb_Apu_State.cpp \
    $(SRC_DIR)/audio/Gb_Oscs.cpp \
    $(SRC_DIR)/audio/Multi_Buffer.cpp \
