/*
 * Gearboy - Nintendo Game Boy Emulator
 * Copyright (C) 2012  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODE_NAMES_H
#define	OPCODE_NAMES_H

struct stOPCodeInfo
{
    const char* name;
    int size;
    int type;
};

static const stOPCodeInfo kOPCodeNames[256] = {
    { "{n}NOP", 1, 0 },
    { "{n}LD {o}BC,$%04X", 3, 3 },
    { "{n}LD {o}(BC),A", 1, 0 },
    { "{n}INC {o}BC", 1, 0 },
    { "{n}INC {o}B", 1, 0 },
    { "{n}DEC {o}B", 1, 0 },
    { "{n}LD {o}B,$%02X", 2, 2 },
    { "{n}RLCA", 1, 0 },
    { "{n}LD {o}($%04X),SP", 3, 3 },
    { "{n}ADD {o}HL,BC", 1, 0 },
    { "{n}LD {o}A,(BC)", 1, 0 },
    { "{n}DEC {o}BC", 1, 0 },
    { "{n}INC {o}C", 1, 0 },
    { "{n}DEC {o}C", 1, 0 },
    { "{n}LD {o}C,$%02X", 2, 2 },
    { "{n}RRCA", 1, 0 },

    { "{n}STOP", 2, 0 },
    { "{n}LD {o}DE,$%04X", 3, 3 },
    { "{n}LD {o}(DE),A", 1, 0 },
    { "{n}INC {o}DE", 1, 0 },
    { "{n}INC {o}D", 1, 0 },
    { "{n}DEC {o}D", 1, 0 },
    { "{n}LD {o}D,$%02X", 2, 2 },
    { "{n}RLA", 1, 0 },
    { "{n}JR {o}$%04X  {e}[%+d]", 2, 5 },
    { "{n}ADD {o}HL,DE", 1, 0 },
    { "{n}LD {o}A,(DE)", 1, 0 },
    { "{n}DEC {o}DE", 1, 0 },
    { "{n}INC {o}E", 1, 0 },
    { "{n}DEC {o}E", 1, 0 },
    { "{n}LD {o}E,$%02X", 2, 2 },
    { "{n}RRA", 1, 0 },

    { "{n}JR {o}NZ,$%04X  {e}[%+d]", 2, 5 },
    { "{n}LD {o}HL,$%04X", 3, 3 },
    { "{n}LD {o}(HL+),A", 1, 0 },
    { "{n}INC {o}HL", 1, 0 },
    { "{n}INC {o}H", 1, 0 },
    { "{n}DEC {o}H", 1, 0 },
    { "{n}LD {o}H,$%02X", 2, 2 },
    { "{n}DAA", 1, 0 },
    { "{n}JR {o}Z,$%04X  {e}[%+d]", 2, 5 },
    { "{n}ADD {o}HL,HL", 1, 0 },
    { "{n}LD {o}A,(HL+)", 1, 0 },
    { "{n}DEC {o}HL", 1, 0 },
    { "{n}INC {o}L", 1, 0 },
    { "{n}DEC {o}L", 1, 0 },
    { "{n}LD {o}L,$%02X", 2, 2 },
    { "{n}CPL", 1, 0 },

    { "{n}JR {o}NC,$%04X  {e}[%+d]", 2, 5 },
    { "{n}LD {o}SP,$%04X", 3, 3 },
    { "{n}LD {o}(HL-),A", 1, 0 },
    { "{n}INC {o}SP", 1, 0 },
    { "{n}INC {o}(HL)", 1, 0 },
    { "{n}DEC {o}(HL)", 1, 0 },
    { "{n}LD {o}(HL),$%02X", 2, 2 },
    { "{n}SCF", 1, 0 },
    { "{n}JR {o}C,$%04X  {e}[%+d]", 2, 5 },
    { "{n}ADD {o}HL,SP", 1, 0 },
    { "{n}LD {o}A,(HL-)", 1, 0 },
    { "{n}DEC {o}SP", 1, 0 },
    { "{n}INC {o}A", 1, 0 },
    { "{n}DEC {o}A", 1, 0 },
    { "{n}LD {o}A,$%02X", 2, 2 },
    { "{n}CCF", 1, 0 },

    { "{n}LD {o}B,B", 1, 0 },
    { "{n}LD {o}B,C", 1, 0 },
    { "{n}LD {o}B,D", 1, 0 },
    { "{n}LD {o}B,E", 1, 0 },
    { "{n}LD {o}B,H", 1, 0 },
    { "{n}LD {o}B,L", 1, 0 },
    { "{n}LD {o}B,(HL)", 1, 0 },
    { "{n}LD {o}B,A", 1, 0 },
    { "{n}LD {o}C,B", 1, 0 },
    { "{n}LD {o}C,C", 1, 0 },
    { "{n}LD {o}C,D", 1, 0 },
    { "{n}LD {o}C,E", 1, 0 },
    { "{n}LD {o}C,H", 1, 0 },
    { "{n}LD {o}C,L", 1, 0 },
    { "{n}LD {o}C,(HL)", 1, 0 },
    { "{n}LD {o}C,A", 1, 0 },

    { "{n}LD {o}D,B", 1, 0 },
    { "{n}LD {o}D,C", 1, 0 },
    { "{n}LD {o}D,D", 1, 0 },
    { "{n}LD {o}D,E", 1, 0 },
    { "{n}LD {o}D,H", 1, 0 },
    { "{n}LD {o}D,L", 1, 0 },
    { "{n}LD {o}D,(HL)", 1, 0 },
    { "{n}LD {o}D,A", 1, 0 },
    { "{n}LD {o}E,B", 1, 0 },
    { "{n}LD {o}E,C", 1, 0 },
    { "{n}LD {o}E,D", 1, 0 },
    { "{n}LD {o}E,E", 1, 0 },
    { "{n}LD {o}E,H", 1, 0 },
    { "{n}LD {o}E,L", 1, 0 },
    { "{n}LD {o}E,(HL)", 1, 0 },
    { "{n}LD {o}E,A", 1, 0 },

    { "{n}LD {o}H,B", 1, 0 },
    { "{n}LD {o}H,C", 1, 0 },
    { "{n}LD {o}H,D", 1, 0 },
    { "{n}LD {o}H,E", 1, 0 },
    { "{n}LD {o}H,H", 1, 0 },
    { "{n}LD {o}H,L", 1, 0 },
    { "{n}LD {o}H,(HL)", 1, 0 },
    { "{n}LD {o}H,A", 1, 0 },
    { "{n}LD {o}L,B", 1, 0 },
    { "{n}LD {o}L,C", 1, 0 },
    { "{n}LD {o}L,D", 1, 0 },
    { "{n}LD {o}L,E", 1, 0 },
    { "{n}LD {o}L,H", 1, 0 },
    { "{n}LD {o}L,L", 1, 0 },
    { "{n}LD {o}L,(HL)", 1, 0 },
    { "{n}LD {o}L,A", 1, 0 },

    { "{n}LD {o}(HL),B", 1, 0 },
    { "{n}LD {o}(HL),C", 1, 0 },
    { "{n}LD {o}(HL),D", 1, 0 },
    { "{n}LD {o}(HL),E", 1, 0 },
    { "{n}LD {o}(HL),H", 1, 0 },
    { "{n}LD {o}(HL),L", 1, 0 },
    { "{n}HALT", 1, 0 },
    { "{n}LD {o}(HL),A", 1, 0 },
    { "{n}LD {o}A,B", 1, 0 },
    { "{n}LD {o}A,C", 1, 0 },
    { "{n}LD {o}A,D", 1, 0 },
    { "{n}LD {o}A,E", 1, 0 },
    { "{n}LD {o}A,H", 1, 0 },
    { "{n}LD {o}A,L", 1, 0 },
    { "{n}LD {o}A,(HL)", 1, 0 },
    { "{n}LD {o}A,A", 1, 0 },

    { "{n}ADD {o}A,B", 1, 0 },
    { "{n}ADD {o}A,C", 1, 0 },
    { "{n}ADD {o}A,D", 1, 0 },
    { "{n}ADD {o}A,E", 1, 0 },
    { "{n}ADD {o}A,H", 1, 0 },
    { "{n}ADD {o}A,L", 1, 0 },
    { "{n}ADD {o}A,(HL)", 1, 0 },
    { "{n}ADD {o}A,A", 1, 0 },
    { "{n}ADC {o}A,B", 1, 0 },
    { "{n}ADC {o}A,C", 1, 0 },
    { "{n}ADC {o}A,D", 1, 0 },
    { "{n}ADC {o}A,E", 1, 0 },
    { "{n}ADC {o}A,H", 1, 0 },
    { "{n}ADC {o}A,L", 1, 0 },
    { "{n}ADC {o}A,(HL)", 1, 0 },
    { "{n}ADC {o}A,A", 1, 0 },

    { "{n}SUB {o}B", 1, 0 },
    { "{n}SUB {o}C", 1, 0 },
    { "{n}SUB {o}D", 1, 0 },
    { "{n}SUB {o}E", 1, 0 },
    { "{n}SUB {o}H", 1, 0 },
    { "{n}SUB {o}L", 1, 0 },
    { "{n}SUB {o}(HL)", 1, 0 },
    { "{n}SUB {o}A", 1, 0 },
    { "{n}SBC {o}A,B", 1, 0 },
    { "{n}SBC {o}A,C", 1, 0 },
    { "{n}SBC {o}A,D", 1, 0 },
    { "{n}SBC {o}A,E", 1, 0 },
    { "{n}SBC {o}A,H", 1, 0 },
    { "{n}SBC {o}A,L", 1, 0 },
    { "{n}SBC {o}A,(HL)", 1, 0 },
    { "{n}SBC {o}A,A", 1, 0 },

    { "{n}AND {o}B", 1, 0 },
    { "{n}AND {o}C", 1, 0 },
    { "{n}AND {o}D", 1, 0 },
    { "{n}AND {o}E", 1, 0 },
    { "{n}AND {o}H", 1, 0 },
    { "{n}AND {o}L", 1, 0 },
    { "{n}AND {o}(HL)", 1, 0 },
    { "{n}AND {o}A", 1, 0 },
    { "{n}XOR {o}B", 1, 0 },
    { "{n}XOR {o}C", 1, 0 },
    { "{n}XOR {o}D", 1, 0 },
    { "{n}XOR {o}E", 1, 0 },
    { "{n}XOR {o}H", 1, 0 },
    { "{n}XOR {o}L", 1, 0 },
    { "{n}XOR {o}(HL)", 1, 0 },
    { "{n}XOR {o}A", 1, 0 },

    { "{n}OR {o}B", 1, 0 },
    { "{n}OR {o}C", 1, 0 },
    { "{n}OR {o}D", 1, 0 },
    { "{n}OR {o}E", 1, 0 },
    { "{n}OR {o}H", 1, 0 },
    { "{n}OR {o}L", 1, 0 },
    { "{n}OR {o}(HL)", 1, 0 },
    { "{n}OR {o}A", 1, 0 },
    { "{n}CP {o}B", 1, 0 },
    { "{n}CP {o}C", 1, 0 },
    { "{n}CP {o}D", 1, 0 },
    { "{n}CP {o}E", 1, 0 },
    { "{n}CP {o}H", 1, 0 },
    { "{n}CP {o}L", 1, 0 },
    { "{n}CP {o}(HL)", 1, 0 },
    { "{n}CP {o}A", 1, 0 },

    { "{n}RET {o}NZ", 1, 0 },
    { "{n}POP {o}BC", 1, 0 },
    { "{n}JP {o}NZ,$%04X", 3, 3 },
    { "{n}JP {o}$%04X", 3, 3 },
    { "{n}CALL {o}NZ,$%04X", 3, 3 },
    { "{n}PUSH {o}BC", 1, 0 },
    { "{n}ADD {o}A,$%02X", 2, 2 },
    { "{n}RST {o}$00", 1, 0 },
    { "{n}RET {o}Z", 1, 0 },
    { "{n}RET", 1, 0 },
    { "{n}JP {o}Z,$%04X", 3, 3 },
    { "{n}cb opcode", 1, 0 },
    { "{n}CALL {o}Z,$%04X", 3, 3 },
    { "{n}CALL {o}$%04X", 3, 3 },
    { "{n}ADC {o}A,$%02X", 2, 2 },
    { "{n}RST {o}$08", 1, 0 },

    { "{n}RET {o}NC", 1, 0 },
    { "{n}POP {o}DE", 1, 0 },
    { "{n}JP {o}NC,$%04X", 3, 3 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}CALL {o}NC,$%04X", 3, 3 },
    { "{n}PUSH {o}DE", 1, 0 },
    { "{n}SUB {o}$%02X", 2, 2 },
    { "{n}RST {o}$10", 1, 0 },
    { "{n}RET {o}C", 1, 0 },
    { "{n}RETI", 1, 0 },
    { "{n}JP {o}C,$%04X", 3, 3 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}CALL {o}C,$%04X", 3, 3 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}SBC {o}A,$%02X", 2, 2 },
    { "{n}RST {o}$18", 1, 0 },

    { "{n}LD {o}($FF00+$%02X),A", 2, 2 },
    { "{n}POP {o}HL", 1, 0 },
    { "{n}LD {o}($FF00+C),A", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}PUSH {o}HL", 1, 0 },
    { "{n}AND {o}$%02X", 2, 2 },
    { "{n}RST {o}$20", 1, 0 },
    { "{n}ADD {o}SP,%+d", 2, 1 },
    { "{n}JP {o}(HL)", 1, 0 },
    { "{n}LD {o}($%04X),A", 3, 3 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}XOR {o}$%02X", 2, 2 },
    { "{n}RST {o}$28", 1, 0 },

    { "{n}LD {o}A,($FF00+$%02X)", 2, 2 },
    { "{n}POP {o}AF", 1, 0 },
    { "{n}LD {o}A,($FF00+C)", 1, 0 },
    { "{n}DI", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}PUSH {o}AF", 1, 0 },
    { "{n}OR {o}$%02X", 2, 2 },
    { "{n}RST {o}$30", 1, 0 },
    { "{n}LD {o}HL,(SP%+d)", 2, 1 },
    { "{n}LD {o}SP,HL", 1, 0 },
    { "{n}LD {o}A,($%04X)", 3, 3 },
    { "{n}EI", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}[UNUSED]", 1, 0 },
    { "{n}CP {o}$%02X", 2, 2 },
    { "{n}RST {o}$38", 1, 0 }
};

static const stOPCodeInfo kOPCodeCBNames[256] = {
    { "{n}RLC {o}B", 2, 0 },
    { "{n}RLC {o}C", 2, 0 },
    { "{n}RLC {o}D", 2, 0 },
    { "{n}RLC {o}E", 2, 0 },
    { "{n}RLC {o}H", 2, 0 },
    { "{n}RLC {o}L", 2, 0 },
    { "{n}RLC {o}(HL)", 2, 0 },
    { "{n}RLC {o}A", 2, 0 },
    { "{n}RRC {o}B", 2, 0 },
    { "{n}RRC {o}C", 2, 0 },
    { "{n}RRC {o}D", 2, 0 },
    { "{n}RRC {o}E", 2, 0 },
    { "{n}RRC {o}H", 2, 0 },
    { "{n}RRC {o}L", 2, 0 },
    { "{n}RRC {o}(HL)", 2, 0 },
    { "{n}RRC {o}A", 2, 0 },

    { "{n}RL {o}B", 2, 0 },
    { "{n}RL {o}C", 2, 0 },
    { "{n}RL {o}D", 2, 0 },
    { "{n}RL {o}E", 2, 0 },
    { "{n}RL {o}H", 2, 0 },
    { "{n}RL {o}L", 2, 0 },
    { "{n}RL {o}(HL)", 2, 0 },
    { "{n}RL {o}A", 2, 0 },
    { "{n}RR {o}B", 2, 0 },
    { "{n}RR {o}C", 2, 0 },
    { "{n}RR {o}D", 2, 0 },
    { "{n}RR {o}E", 2, 0 },
    { "{n}RR {o}H", 2, 0 },
    { "{n}RR {o}L", 2, 0 },
    { "{n}RR {o}(HL)", 2, 0 },
    { "{n}RR {o}A", 2, 0 },

    { "{n}SLA {o}B", 2, 0 },
    { "{n}SLA {o}C", 2, 0 },
    { "{n}SLA {o}D", 2, 0 },
    { "{n}SLA {o}E", 2, 0 },
    { "{n}SLA {o}H", 2, 0 },
    { "{n}SLA {o}L", 2, 0 },
    { "{n}SLA {o}(HL)", 2, 0 },
    { "{n}SLA {o}A", 2, 0 },
    { "{n}SRA {o}B", 2, 0 },
    { "{n}SRA {o}C", 2, 0 },
    { "{n}SRA {o}D", 2, 0 },
    { "{n}SRA {o}E", 2, 0 },
    { "{n}SRA {o}H", 2, 0 },
    { "{n}SRA {o}L", 2, 0 },
    { "{n}SRA {o}(HL)", 2, 0 },
    { "{n}SRA {o}A", 2, 0 },

    { "{n}SWAP {o}B", 2, 0 },
    { "{n}SWAP {o}C", 2, 0 },
    { "{n}SWAP {o}D", 2, 0 },
    { "{n}SWAP {o}E", 2, 0 },
    { "{n}SWAP {o}H", 2, 0 },
    { "{n}SWAP {o}L", 2, 0 },
    { "{n}SWAP {o}(HL)", 2, 0 },
    { "{n}SWAP {o}A", 2, 0 },
    { "{n}SRL {o}B", 2, 0 },
    { "{n}SRL {o}C", 2, 0 },
    { "{n}SRL {o}D", 2, 0 },
    { "{n}SRL {o}E", 2, 0 },
    { "{n}SRL {o}H", 2, 0 },
    { "{n}SRL {o}L", 2, 0 },
    { "{n}SRL {o}(HL)", 2, 0 },
    { "{n}SRL {o}A", 2, 0 },

    { "{n}BIT {o}0,B", 2, 0 },
    { "{n}BIT {o}0,C", 2, 0 },
    { "{n}BIT {o}0,D", 2, 0 },
    { "{n}BIT {o}0,E", 2, 0 },
    { "{n}BIT {o}0,H", 2, 0 },
    { "{n}BIT {o}0,L", 2, 0 },
    { "{n}BIT {o}0,(HL)", 2, 0 },
    { "{n}BIT {o}0,A", 2, 0 },
    { "{n}BIT {o}1,B", 2, 0 },
    { "{n}BIT {o}1,C", 2, 0 },
    { "{n}BIT {o}1,D", 2, 0 },
    { "{n}BIT {o}1,E", 2, 0 },
    { "{n}BIT {o}1,H", 2, 0 },
    { "{n}BIT {o}1,L", 2, 0 },
    { "{n}BIT {o}1,(HL)", 2, 0 },
    { "{n}BIT {o}1,A", 2, 0 },

    { "{n}BIT {o}2,B", 2, 0 },
    { "{n}BIT {o}2,C", 2, 0 },
    { "{n}BIT {o}2,D", 2, 0 },
    { "{n}BIT {o}2,E", 2, 0 },
    { "{n}BIT {o}2,H", 2, 0 },
    { "{n}BIT {o}2,L", 2, 0 },
    { "{n}BIT {o}2,(HL)", 2, 0 },
    { "{n}BIT {o}2,A", 2, 0 },
    { "{n}BIT {o}3,B", 2, 0 },
    { "{n}BIT {o}3,C", 2, 0 },
    { "{n}BIT {o}3,D", 2, 0 },
    { "{n}BIT {o}3,E", 2, 0 },
    { "{n}BIT {o}3,H", 2, 0 },
    { "{n}BIT {o}3,L", 2, 0 },
    { "{n}BIT {o}3,(HL)", 2, 0 },
    { "{n}BIT {o}3,A", 2, 0 },

    { "{n}BIT {o}4,B", 2, 0 },
    { "{n}BIT {o}4,C", 2, 0 },
    { "{n}BIT {o}4,D", 2, 0 },
    { "{n}BIT {o}4,E", 2, 0 },
    { "{n}BIT {o}4,H", 2, 0 },
    { "{n}BIT {o}4,L", 2, 0 },
    { "{n}BIT {o}4,(HL)", 2, 0 },
    { "{n}BIT {o}4,A", 2, 0 },
    { "{n}BIT {o}5,B", 2, 0 },
    { "{n}BIT {o}5,C", 2, 0 },
    { "{n}BIT {o}5,D", 2, 0 },
    { "{n}BIT {o}5,E", 2, 0 },
    { "{n}BIT {o}5,H", 2, 0 },
    { "{n}BIT {o}5,L", 2, 0 },
    { "{n}BIT {o}5,(HL)", 2, 0 },
    { "{n}BIT {o}5,A", 2, 0 },

    { "{n}BIT {o}6,B", 2, 0 },
    { "{n}BIT {o}6,C", 2, 0 },
    { "{n}BIT {o}6,D", 2, 0 },
    { "{n}BIT {o}6,E", 2, 0 },
    { "{n}BIT {o}6,H", 2, 0 },
    { "{n}BIT {o}6,L", 2, 0 },
    { "{n}BIT {o}6,(HL)", 2, 0 },
    { "{n}BIT {o}6,A", 2, 0 },
    { "{n}BIT {o}7,B", 2, 0 },
    { "{n}BIT {o}7,C", 2, 0 },
    { "{n}BIT {o}7,D", 2, 0 },
    { "{n}BIT {o}7,E", 2, 0 },
    { "{n}BIT {o}7,H", 2, 0 },
    { "{n}BIT {o}7,L", 2, 0 },
    { "{n}BIT {o}7,(HL)", 2, 0 },
    { "{n}BIT {o}7,A", 2, 0 },

    { "{n}RES {o}0,B", 2, 0 },
    { "{n}RES {o}0,C", 2, 0 },
    { "{n}RES {o}0,D", 2, 0 },
    { "{n}RES {o}0,E", 2, 0 },
    { "{n}RES {o}0,H", 2, 0 },
    { "{n}RES {o}0,L", 2, 0 },
    { "{n}RES {o}0,(HL)", 2, 0 },
    { "{n}RES {o}0,A", 2, 0 },
    { "{n}RES {o}1,B", 2, 0 },
    { "{n}RES {o}1,C", 2, 0 },
    { "{n}RES {o}1,D", 2, 0 },
    { "{n}RES {o}1,E", 2, 0 },
    { "{n}RES {o}1,H", 2, 0 },
    { "{n}RES {o}1,L", 2, 0 },
    { "{n}RES {o}1,(HL)", 2, 0 },
    { "{n}RES {o}1,A", 2, 0 },

    { "{n}RES {o}2,B", 2, 0 },
    { "{n}RES {o}2,C", 2, 0 },
    { "{n}RES {o}2,D", 2, 0 },
    { "{n}RES {o}2,E", 2, 0 },
    { "{n}RES {o}2,H", 2, 0 },
    { "{n}RES {o}2,L", 2, 0 },
    { "{n}RES {o}2,(HL)", 2, 0 },
    { "{n}RES {o}2,A", 2, 0 },
    { "{n}RES {o}3,B", 2, 0 },
    { "{n}RES {o}3,C", 2, 0 },
    { "{n}RES {o}3,D", 2, 0 },
    { "{n}RES {o}3,E", 2, 0 },
    { "{n}RES {o}3,H", 2, 0 },
    { "{n}RES {o}3,L", 2, 0 },
    { "{n}RES {o}3,(HL)", 2, 0 },
    { "{n}RES {o}3,A", 2, 0 },

    { "{n}RES {o}4,B", 2, 0 },
    { "{n}RES {o}4,C", 2, 0 },
    { "{n}RES {o}4,D", 2, 0 },
    { "{n}RES {o}4,E", 2, 0 },
    { "{n}RES {o}4,H", 2, 0 },
    { "{n}RES {o}4,L", 2, 0 },
    { "{n}RES {o}4,(HL)", 2, 0 },
    { "{n}RES {o}4,A", 2, 0 },
    { "{n}RES {o}5,B", 2, 0 },
    { "{n}RES {o}5,C", 2, 0 },
    { "{n}RES {o}5,D", 2, 0 },
    { "{n}RES {o}5,E", 2, 0 },
    { "{n}RES {o}5,H", 2, 0 },
    { "{n}RES {o}5,L", 2, 0 },
    { "{n}RES {o}5,(HL)", 2, 0 },
    { "{n}RES {o}5,A", 2, 0 },

    { "{n}RES {o}6,B", 2, 0 },
    { "{n}RES {o}6,C", 2, 0 },
    { "{n}RES {o}6,D", 2, 0 },
    { "{n}RES {o}6,E", 2, 0 },
    { "{n}RES {o}6,H", 2, 0 },
    { "{n}RES {o}6,L", 2, 0 },
    { "{n}RES {o}6,(HL)", 2, 0 },
    { "{n}RES {o}6,A", 2, 0 },
    { "{n}RES {o}7,B", 2, 0 },
    { "{n}RES {o}7,C", 2, 0 },
    { "{n}RES {o}7,D", 2, 0 },
    { "{n}RES {o}7,E", 2, 0 },
    { "{n}RES {o}7,H", 2, 0 },
    { "{n}RES {o}7,L", 2, 0 },
    { "{n}RES {o}7,(HL)", 2, 0 },
    { "{n}RES {o}7,A", 2, 0 },

    { "{n}SET {o}0,B", 2, 0 },
    { "{n}SET {o}0,C", 2, 0 },
    { "{n}SET {o}0,D", 2, 0 },
    { "{n}SET {o}0,E", 2, 0 },
    { "{n}SET {o}0,H", 2, 0 },
    { "{n}SET {o}0,L", 2, 0 },
    { "{n}SET {o}0,(HL)", 2, 0 },
    { "{n}SET {o}0,A", 2, 0 },
    { "{n}SET {o}1,B", 2, 0 },
    { "{n}SET {o}1,C", 2, 0 },
    { "{n}SET {o}1,D", 2, 0 },
    { "{n}SET {o}1,E", 2, 0 },
    { "{n}SET {o}1,H", 2, 0 },
    { "{n}SET {o}1,L", 2, 0 },
    { "{n}SET {o}1,(HL)", 2, 0 },
    { "{n}SET {o}1,A", 2, 0 },

    { "{n}SET {o}2,B", 2, 0 },
    { "{n}SET {o}2,C", 2, 0 },
    { "{n}SET {o}2,D", 2, 0 },
    { "{n}SET {o}2,E", 2, 0 },
    { "{n}SET {o}2,H", 2, 0 },
    { "{n}SET {o}2,L", 2, 0 },
    { "{n}SET {o}2,(HL)", 2, 0 },
    { "{n}SET {o}2,A", 2, 0 },
    { "{n}SET {o}3,B", 2, 0 },
    { "{n}SET {o}3,C", 2, 0 },
    { "{n}SET {o}3,D", 2, 0 },
    { "{n}SET {o}3,E", 2, 0 },
    { "{n}SET {o}3,H", 2, 0 },
    { "{n}SET {o}3,L", 2, 0 },
    { "{n}SET {o}3,(HL)", 2, 0 },
    { "{n}SET {o}3,A", 2, 0 },

    { "{n}SET {o}4,B", 2, 0 },
    { "{n}SET {o}4,C", 2, 0 },
    { "{n}SET {o}4,D", 2, 0 },
    { "{n}SET {o}4,E", 2, 0 },
    { "{n}SET {o}4,H", 2, 0 },
    { "{n}SET {o}4,L", 2, 0 },
    { "{n}SET {o}4,(HL)", 2, 0 },
    { "{n}SET {o}4,A", 2, 0 },
    { "{n}SET {o}5,B", 2, 0 },
    { "{n}SET {o}5,C", 2, 0 },
    { "{n}SET {o}5,D", 2, 0 },
    { "{n}SET {o}5,E", 2, 0 },
    { "{n}SET {o}5,H", 2, 0 },
    { "{n}SET {o}5,L", 2, 0 },
    { "{n}SET {o}5,(HL)", 2, 0 },
    { "{n}SET {o}5,A", 2, 0 },

    { "{n}SET {o}6,B", 2, 0 },
    { "{n}SET {o}6,C", 2, 0 },
    { "{n}SET {o}6,D", 2, 0 },
    { "{n}SET {o}6,E", 2, 0 },
    { "{n}SET {o}6,H", 2, 0 },
    { "{n}SET {o}6,L", 2, 0 },
    { "{n}SET {o}6,(HL)", 2, 0 },
    { "{n}SET {o}6,A", 2, 0 },
    { "{n}SET {o}7,B", 2, 0 },
    { "{n}SET {o}7,C", 2, 0 },
    { "{n}SET {o}7,D", 2, 0 },
    { "{n}SET {o}7,E", 2, 0 },
    { "{n}SET {o}7,H", 2, 0 },
    { "{n}SET {o}7,L", 2, 0 },
    { "{n}SET {o}7,(HL)", 2, 0 },
    { "{n}SET {o}7,A", 2, 0 }
};

#endif	/* OPCODE_NAMES_H */

